### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Samgisaninja** [Samgisaninja/sillyo#1]
- [x] Fix Cydia complaining about duplicated sources
- [x] Fix giveMeRoot
- [x] Force Sileo to load the bingner repo (this appears to be because of Sileo's lack of support for repo formats other than the one "most repos use", same issue occurs with BigBoss)
- [x] Fix Sileo's respring button when package (un/re)installation completes so that it doesn't need tweak injector
